version: "3.4"

services:

  scrobbler-ui:
    build:
      context: .
    environment:
      API_URL: "http://192.168.1.37:8000/"
    ports:
      - 80:80

  scrobbler-ui-prod:
    image: harvzor/scrobbler-ui:latest
    ports:
      - 80:80
